development:
  adapter: postgresql
  database: demo_dev
  host: localhost

test:
  adapter: postgresql
  database: demo_test
  host: localhost

production:
  adapter: postgresql
  database: demo_prod
