# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 07f22c005d489715cd993dfc28a3f3d8ad498bd3cc1f79005fa3ee096006f55d7b3a6c605f17656d54be171bdafaf19c2eaf1d72c1d424f17164bc40094e1ebd

test:
  secret_key_base: 243eef578711e3ec09ac0c2ae909928dc0770a8d9cb13604bb56315a5cd02209208a72638f9773b4f317b50fba4018c770dadc396e1734930ab88fb8d9391ec7

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
